# Generated by Django 2.2.1 on 2019-05-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='pickupTime',
            new_name='everyTime',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='pickupDate',
            new_name='firstPickupDate',
        ),
        migrations.AlterField(
            model_name='join',
            name='contactType',
            field=models.CharField(choices=[('whatsapp', 'Whatsapp'), ('line', 'Line'), ('email', 'Email'), ('instagram', 'Instagram')], max_length=52),
        ),
        migrations.AlterField(
            model_name='later',
            name='contactType',
            field=models.CharField(choices=[('whatsapp', 'Whatsapp'), ('line', 'Line'), ('email', 'Email'), ('instagram', 'Instagram')], max_length=52),
        ),
        migrations.AlterField(
            model_name='question',
            name='contactType',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'Whatsapp'), ('line', 'Line'), ('instagram', 'Instagram')], max_length=52),
        ),
    ]
